info: "OpenAIRE Matomo Tracker"

Matomo_Parameters:
  #Matomo tracker Endpoint
  matomo_url: "https://analytics.openaire.eu/"
  #Repository Base Url
  repository_base_url: "https://repository.com"
  #Matomo Repository Site ID
  idSite: 314
  #Matomo authenticastion token
  token_auth: "32846584f571be9b57488bf4088f30ea"
  #matomo parameters (default values)
  delay_after_failure: 10
  default_max_attempts: 3
  default_socket_timeout: 300
  ip_anonymization: false

  # Number of recorders. It should be set to the number of CPU cores in your server.
  # You can also experiment with higher values which may increase performance until a certain point
  recorders: 1

 #Maximum number of log entries to record in one tracking request. 
  max_payload: 100

  #OAI-PMH Configuration
  oaipmh_preamble: "oai:repository.site:"
  
  #Metadata Location (supports multiple locations and regular expressions)
  tracking_metadata:
  - "/([0-9]*)/(?!pdf)$"
  
  #Item Location (supports multiple locations and regular expressions)
  tracking_download:
  - "/([0-9]*)/[0-9]*\\w.*pdf"
